### ISSUE TITLE
1- Header yazı aralığı

### ISSUE THREAD

**Issue by lalenas** [node101-io/cryptist#1]
selammm eline sağlık öncelikle 
![image](https://github.com/node101-io/cryptist/assets/138670978/24812f08-452c-4415-8b13-c43051a3a5ba)
headerda yazılar birbirne baya yakın görüyor aralarını açabilir miyiz

**Comment by tunntun** [comment]
<img width="1512" alt="Screenshot 2023-09-09 at 02 45 28" src="https://github.com/node101-io/cryptist/assets/108955016/fb8bf247-b8ee-4679-ab29-e9654c0a67cd">

Buna ne dersin?
