### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by lalenas** [node101-io/cryptist#2]
![image](https://github.com/node101-io/cryptist/assets/138670978/c37d266b-b2ed-4455-ada7-dcc46eec4540)
bu ekranda diğer ekranın elementi olan daire aşağıda biraz gözüküyor onu gözükmeyecek şekilde ayarlayabilir miyiz <3
Yazılar da birbirine yakın harf aralığını açabilir misin

**Comment by tunntun** [comment]
<img width="1624" alt="image" src="https://github.com/node101-io/cryptist/assets/108955016/27ab274a-f1c0-4f66-af9d-39210eb6b5eb">

**Comment by lalenas** [comment]
done
