### ISSUE TITLE
Sponsor sayfasının düzeni

### ISSUE THREAD

**Issue by lalenas** [node101-io/cryptist#6]
![image](https://github.com/node101-io/cryptist/assets/138670978/d5bc9dde-65b6-4ac7-a08b-f5cd5eda4f68)
Would you like to be a sponsor to Cryptİst? Reach us! yazısı sponsor kutularına daha yakın olmalı, arkada gözüken geometrik materyal konuşmacıların olduğu sayfada olmamalı tamamen sponsor sayfasına ait sponsor kutulatını kücültüp geometrik materyali aşağı indirebilir miyiz

**Comment by tunntun** [comment]
<img width="1624" alt="image" src="https://github.com/node101-io/cryptist/assets/108955016/c1a20abb-d85a-4425-ae5b-6c2391a1924b">

<img width="1624" alt="image" src="https://github.com/node101-io/cryptist/assets/108955016/49db3c66-f838-4ec0-9064-94f278aebfdf">

**Comment by lalenas** [comment]
done
