### ISSUE TITLE
Schedule sayfası düzeni

### ISSUE THREAD

**Issue by lalenas** [node101-io/cryptist#7]
![image](https://github.com/node101-io/cryptist/assets/138670978/00d69dad-4b96-4f64-8573-8a7f9cac536c)
Schedule ve lorem ipsum yazıları daha aşağıd aarkasındaki görsel daha büyük olmalı

**Comment by lalenas** [comment]
![image](https://github.com/node101-io/cryptist/assets/138670978/b2f36a05-e6e8-47f4-8aaf-f0de3cdc2ee8)
 yazılar regular olamlı ve aralarını açabilir miyiz sıkışık görünümünü azaltalım

**Comment by tunntun** [comment]
<img width="1624" alt="image" src="https://github.com/node101-io/cryptist/assets/108955016/5491035b-9b7f-45cd-bd92-277e33d56e78">

**Comment by lalenas** [comment]
done
