### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lalenas** [node101-io/cryptist#8]
![image](https://github.com/node101-io/cryptist/assets/138670978/457965ad-0df8-4767-89b4-775d2f8dfdf2)
 Get your tickets now! Don’t miss the agenda of the Zero-Knowledge Ecosystem! See you in Cryptİst! yazısı daha büyük ve 2 satır halinde oralanmış olmalıdır 
 Cryptist yazısı daha büyük ve daha kalın almalıdır harf aralığı ise daha açık 
 Subscribe bölümünü göremedim 
 Pages  Contact Us kısmı küçük kalmış font sizeları tasarımdaki gibi düzenleyebilir miyiz
 
![image](https://github.com/node101-io/cryptist/assets/138670978/84b500f4-ea8d-47e6-bb5e-8ad02c4c9d9a)
 bu bölümüde ekleyebilir miyiz hatta mail kısmı burada olmalı kopyalayacağı icon ise hemen yanında

**Comment by tunntun** [comment]
burada contact us kısmını tek satırda göstermede bir problem yaşıyorum ve asla anlamadım. yarın soracağım, orayı düzeltirim. mail bülteni olayının nasıl yapılacağını öğrenmem lazım orası yok o yüzden

<img width="1624" alt="image" src="https://github.com/node101-io/cryptist/assets/108955016/2549805d-ce86-4bf3-8437-8eba3ae6730c">
